version: '3.8'

services:
  web:
    build: .
    container_name: dev_web
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./html:/var/www/html
      - ./certs:/etc/ssl/certs
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: dev_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"

volumes:
  db_data:
