version: '3.8'

services:
  app:
    build: .
    container_name: prod_app
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./html:/var/www/html
      - ./certs:/etc/ssl/certs
    env_file:
      - .env
