services:

  web:
    build: apache
    hostname: web
    ports:
      - 8000:80
      - 443:443
    networks:
      rede_test:
        aliases:
          - a23bernalrc.ddnsfree.com
          - www.a23bernalrc.ddnsfree.com
    volumes:
      - ./app:/app
      - ./apache/drupal.conf:/etc/apache2/sites-enabled/drupal.conf
      - ./certs:/certs